


#define  LVCM_RSI_DEFINE  			  RSI_SN_ADWIN,  \
									  RSI_SN_TVWIN,  \
									  RSI_SN_BAR_LITTLE, \
									  RSI_SN_BAR_BLUE_NORMAL, \
									  RSI_SN_BAR_YELLOW_HL,\
									  RSI_SN_BAR_VERTICAL,\
									  RSI_SN_BAR_CROSS,\
									  RSI_SN_BAR_BACKGROUND, \
									  RSI_SN_BUTTON_SET_BLUE_SH, \
									  RSI_SN_BUTTON_SET_YELLOW_HL, \
									  RSI_SN_BG, \
									  RSI_SN_BG_TITLE,\
									  RSI_XX_BAR, \
									  RSI_SN_BAR_YELLOW_MIDDLE, \
									  RSI_SN_EMAIL_CONTENT_BG



#if 1
#define LVCM_RSI_STYLE    \
	/*RSI_SN_ADWINSN*/ \
	{  \
		{R_ICON, IM_SN_ADWIN_LEFT}, \
		{R_ICON, IM_SN_ADWIN_MT}, \
		{R_ICON, IM_SN_ADWIN_RIGHT},\
		{R_ICON, IM_SN_ADWIN_MB}, \
		{R_FILL_RECT_TO_BORDER, C_TRANS}, \
		{R_ICON, IM_SN_ADWIN_LT},\
		{R_ICON, IM_SN_ADWIN_RT}, \
		{R_ICON, IM_SN_ADWIN_RB}, \
		{R_ICON, IM_SN_ADWIN_LB}\
	},\
 	 /*RSI_SN_TVWIN*/ \
  { {R_ICON, IM_SN_ADWIN_LEFT}, {R_ICON, IM_SN_ADWIN_MT},{R_ICON, IM_SN_ADWIN_RIGHT},{R_ICON, IM_SN_ADWIN_MB}, {R_FILL_RECT_TO_BORDER, C_TRANS}, {R_ICON, IM_SN_ADWIN_LT},{R_ICON, IM_SN_ADWIN_RT}, {R_ICON, IM_SN_ADWIN_RB}, {R_ICON, IM_SN_ADWIN_LB}},\
  /*RSI_SN_BAR_LITTLE */ \
  { {R_ICON, IM_SN_BAR_LITTLE_LT}, {R_IGNORE},{R_ICON, IM_SN_BAR_LITTLE_RT}, {R_IGNORE}, {R_ICON, IM_SN_BAR_LITTLE_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}}, \
  /*RSI_SN_BAR_BLUE_NORMAL*/ \
  { {R_ICON, IM_SN_BAR_BLUE_LT}, {R_IGNORE}, {R_ICON, IM_SN_BAR_BLUE_RT},	{R_IGNORE},	{R_ICON, IM_SN_BAR_BLUE_MT},	{R_IGNORE}, 	{R_IGNORE},	{R_IGNORE},	{R_IGNORE}},\
  /*RSI_SN_BAR_YELLOW_HL*/ \
  { {R_ICON, IM_SN_BAR_YELLOW_LT}, {R_IGNORE},{R_ICON, IM_SN_BAR_YELLOW_RT}, {R_IGNORE}, {R_ICON, IM_SN_BAR_YELLOW_MT}, 	{R_IGNORE}, 	{R_IGNORE}, 	{R_IGNORE}, 	{R_IGNORE} },\
  /* RSI_SN_BAR_VERTICAL*/ \
  { {R_IGNORE}, {R_ICON, IM_SN_LINE_V}, {R_IGNORE}, {R_ICON, IM_SN_LINE_V},{R_ICON, IM_SN_LINE_V}, {R_IGNORE}, {R_IGNORE},{R_IGNORE}, {R_IGNORE}},\
  /*RSI_SN_BAR_CROSS   */  \
  { {R_ICON, IM_SN_LINE_H}, {R_IGNORE}, {R_ICON, IM_SN_LINE_H},{R_IGNORE}, {R_ICON, IM_SN_LINE_H},  {R_IGNORE}, {R_IGNORE},{R_IGNORE},{R_IGNORE}}, \
  /*RSI_SN_BAR_BACKGROUND	 */  \
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE},{R_IGNORE}, {R_COLOR,RGB24TORGB565(0x12406b)},  {R_IGNORE}, {R_IGNORE},{R_IGNORE},{R_IGNORE}}, \
  /*RSI_SN_BUTTON_SET_BLUE_SH	 */  \
  { {R_ICON, IM_SN_BUTTON_SET_BLUE_LT}, {R_IGNORE}, {R_ICON, IM_SN_BUTTON_SET_BLUE_RT},{R_IGNORE}, {R_ICON, IM_SN_BUTTON_SET_BLUE_MT},  {R_IGNORE}, {R_IGNORE},{R_IGNORE},{R_IGNORE}}, \
  /*RSI_SN_BUTTON_SET_YELLOW_HL    */  \
  { {R_ICON, IM_SN_BUTTON_SET_YELLOW_LT}, {R_IGNORE}, {R_ICON, IM_SN_BUTTON_SET_YELLOW_RT},{R_IGNORE}, {R_ICON, IM_SN_BUTTON_SET_YELLOW_MT},  {R_IGNORE}, {R_IGNORE},{R_IGNORE},{R_IGNORE}}, \
  /*RSI_SN_BG    */  \
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE},{R_IGNORE}, {R_ICON, IM_SN_BG}, {R_IGNORE}, {R_IGNORE},{R_IGNORE},{R_IGNORE}}, \
  /*RSI_SN_BG_TITLE    */  \
  { {R_IGNORE}, {R_ICON, IM_SN_BG_TITLE}, {R_IGNORE},{R_IGNORE}, {R_ICON, R_IGNORE}, {R_IGNORE}, {R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_XX_BAR */\
  { {R_IGNORE}, {R_IGNORE},{R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_SN_BAR_YELLOW_MT}, 	{R_IGNORE}, 	{R_IGNORE}, 	{R_IGNORE}, 	{R_IGNORE} },\
  /*RSI_SN_BAR_YELLOW_MIDDLE*/ \
  { {R_IGNORE}, {R_IGNORE},{R_IGNORE}, {R_IGNORE}, {R_ICON, IM_SN_BAR_YELLOW_MT},	  {R_IGNORE},	  {R_IGNORE},	  {R_IGNORE},	  {R_IGNORE} },\
  /*RSI_SN_EMAIL_CONTENT_BG*/ \
  { {R_ICON,IM_SN_EMAIL_CONTENT_BG_ML},{R_ICON,IM_SN_EMAIL_CONTENT_BG_MT},{R_ICON,IM_SN_EMAIL_CONTENT_BG_MR},{R_ICON,IM_SN_EMAIL_CONTENT_BG_MB},{R_ICON,IM_SN_EMAIL_CONTENT_BG},{R_ICON,IM_SN_EMAIL_CONTENT_BG_LT},{R_ICON,IM_SN_EMAIL_CONTENT_BG_RT},{R_ICON,IM_SN_EMAIL_CONTENT_BG_RB},{R_ICON,IM_SN_EMAIL_CONTENT_BG_LB}},
  #endif
