
#ifndef __Z_LXD_H_
#define __Z_LXD_H_




#define  LXD_RSI_DEFINE            	  RSI_SN_PROGRAM_YELLOW_BAR,\
									  RSI_SN_PROGRAM_BG,\
									  RSI_SN_PROGRAM_BG_BG,\
									  RSI_SN_PROGRAM_SIGNAL_QUA,\
									  RSI_SN_PROGRAM_SIGNAL_STR
#define LXD_RSI_STYLE\
  /*RSI_SN_PROGRAM_YELLOW_BAR*/\
  { {R_ICON, IM_SN_PROGRAM_L}, {R_IGNORE}, {R_ICON, IM_SN_PROGRAM_R}, {R_IGNORE},{R_ICON, IM_SN_PROGRAM_M},{R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},\
  /*RSI_SN_PROGRAM_BG*/\
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE},{R_IGNORE}, {R_ICON, IM_SN_BG}, {R_IGNORE}, {R_IGNORE},{R_IGNORE},{R_IGNORE}}, \
  /*RSI_SN_PROGRAM_BG_BG*/\
  { {R_ICON, IM_SN_PROGRAM_BG_L}, {R_IGNORE}, {R_ICON, IM_SN_PROGRAM_BG_R}, {R_IGNORE}, {R_ICON , IM_SN_PROGRAM_BG_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
  /*RSI_SN_PROGRAM_SIGNAL_QUA*/ \
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_SN_ICON_SIGNAL_QUA_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
   /*RSI_SN_PROGRAM_SIGNAL_STR*/ \
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_SN_ICON_SIGNAL_STR_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},


#endif


