

#define WHM_RSI_DEFINE 			  RSI_SN_SET_BUTTON_SELECT , \
									  RSI_SN_SET_BUTTON_SELECTH, \
									  RSI_SN_SEARCH_SELECT_RIGHT,\
									  RSI_SN_SEARCH_SELECT_LEFT,\
									  RSI_SN_SEARCH_SELECT,\
									  RSI_SN_ALL_BG,\
									  RSI_SN_SEARCH_BAR,\
									  RSI_SN_SEARCH_BAR_FOCUS,\
									  RSI_SN_SEARCH_SELECT_ARROW_RIGHT,\
									  RSI_SN_SEARCH_SELECT_ARROW_LEFT,\
									  RSI_HELP_BG,\
									  RSI_COMM_BG,\
									  RSI_SELECT_ARROW,\
									  RSI_EMAIL_HEAD


#define WHM_RSI_STYLE      \
	/*RSI_SN_SET_BUTTON_SELECT*/ \
  { {R_ICON, IM_SN_BUTTON_SET_BLUE_LT}, {R_IGNORE}, {R_ICON, IM_SN_BUTTON_SET_BLUE_RT}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_SN_BUTTON_SET_BLUE_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
  /*RSI_SN_SET_BUTTON_SELECTH*/ \
  { {R_ICON, IM_SN_BUTTON_SET_YELLOW_LT}, {R_IGNORE}, {R_ICON, IM_SN_BUTTON_SET_YELLOW_RT}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_SN_BUTTON_SET_YELLOW_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
  /*RSI_SN_SEARCH_SELECT_RIGHT*/ \
  { {R_IGNORE}, {R_IGNORE}, {R_ICON, IM_SN_BAR_BLUE_RT}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_SN_BAR_BLUE_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
/*RSI_SN_SEARCH_SELECT_LEFT*/ \
  { {R_ICON, IM_SN_BAR_BLUE_LT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_SN_BAR_BLUE_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
/*RSI_SN_SEARCH_SELECT*/\
  { {R_ICON, IM_SN_BAR_BLUE_LT}, {R_IGNORE}, {R_ICON, IM_SN_BAR_BLUE_RT}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_SN_BAR_BLUE_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
  /*RSI_SN_ALL_BG*/\
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER,IM_SN_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
  /*RSI_SN_SEARCH_BAR*/\
  { {R_ICON, IM_SN_BAR_BLUE_LT}, {R_IGNORE}, {R_ICON, IM_SN_BAR_BLUE_RT}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_SN_BAR_BLUE_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
  /*RSI_SN_SEARCH_BAR_FOCUS*/\
  { {R_ICON, IM_SN_BAR_YELLOW_LT}, {R_IGNORE}, {R_ICON, IM_SN_BAR_YELLOW_RT}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_SN_BAR_YELLOW_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
	/*RSI_SN_SEARCH_SELECT_ARROW_RIGHT*/ \
	{ {R_IGNORE}, {R_IGNORE}, {R_ICON, IM_SN_ICON_ARROW_BAR_RIGHT}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_SN_BAR_BLUE_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
	/*RSI_SN_SEARCH_SELECT_ARROW_LEFT*/ \
	{ {R_ICON, IM_SN_BAR_BLUE_LT}, {R_IGNORE}, {R_ICON, IM_SN_ICON_ARROW_BAR_M}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_SN_BAR_BLUE_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
	/*RSI_HELP_BG*/ \
	{ {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_ICON, IM_SN_HELP_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
	/*RSI_COMM_BG*/ \
	{ {R_ICON, IM_SN_DLG_BGP_LT}, {R_IGNORE}, {R_ICON, IM_SN_DLG_BGP_RT}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_SN_DLG_BGP_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
	/*RSI_SELECT_ARROW*/ \
	{ {R_ICON, IM_SN_ICON_ARROW_BAR_LEFT}, {R_IGNORE}, {R_ICON, IM_SN_ICON_ARROW_BAR_RIGHT}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_SN_BAR_BLUE_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
	/*RSI_EMAIL_HEAD*/ \
	{ {R_FILL_ICON_TO_BORDER, IM_SN_EMAIL_LEFT}, {R_FILL_ICON_TO_BORDER, IM_SN_EMAIL_TOP}, {R_FILL_ICON_TO_BORDER, IM_SN_EMAIL_RIGHT}, {R_FILL_ICON_TO_BORDER,IM_SN_EMAIL_DOWN}, {R_FILL_ICON_TO_BORDER, IM_SN_EMAIL_M}, {R_ICON, IM_SN_EMAIL_LEFT_TOP}, {R_ICON, IM_SN_EMAIL_RIGHT_TOP}, {R_ICON , IM_SN_EMAIL_RIGHT_DOWN},{R_ICON, IM_SN_EMAIL_LEFT_DOWN}},\
  
