
#ifndef __Z_XUXIN_H_
#define __Z_XUXIN_H_




#define  RSI_XUXIN_DEFINE             RSI_SN_COMM_ROOT_BG, \
									  RSI_SN_PREVIEW_TV_WIN,\
									  RSI_SN_ADVERTISEMENT_WIN,\
									  RSI_ICON_CHANNEL,\
									  RSI_MENU_ICON,\
									  RSI_MSG_ICON,\
									  RSI_MANAGER_ICON,\
									  RSI_BOOK_ICON,\
									  RSI_SYS_ICON,\
									  RSI_SN_TITLE_BG,\
									  RSI_SN_CHLIST_SH,\
									  RSI_SN_CHLIST_HL,\
									  RSI_SN_EPG_SH,\
									  RSI_SN_EPG_HL,\
									  RSI_SN_CHEDIT_SH,\
									  RSI_SN_CHEDIT_HL,\
									  RSI_SN_SYSSET_SH,\
									  RSI_SN_SYSSET_HL,\
									  RSI_SN_GAME_SH,\
									  RSI_SN_GAME_HL,\
									  RSI_SN_MSG_SH,\
									  RSI_SN_MSG_HL,\
									  RSI_SN_COMM_PBAR_BG,\
									  RSI_SN_COMM_PBAR_MID,\
									  RSI_SN_VOLUME,\
									  RSI_SN_VOLUME_LABA,\
									  RSI_SN_ICON_LABA,\
									  RSI_SN_HELP_BG2,\
									  RSI_DIG_BG,\
									  RSI_MIN_PROGRESS_BAR_BG,\
									  RSI_MIN_COMM_PBAR_MID,\
									  RSI_SEARCH_BG,\
									  RSI_EMAI_CONTENT_LT,\
									  RSI_EMAI_CONTENT_RT
									  


#define RSI_XUXIN_STYLE\
  /* RSI_SN_COMM_ROOT_BG*/\
  { {R_ICON,IM_SN_BG}, {R_ICON , IM_SN_BG}, {R_ICON,IM_SN_BG}, {R_ICON , IM_SN_BG}, {R_ICON , IM_SN_BG}, {R_ICON , IM_SN_BG}, {R_ICON , IM_SN_BG}, {R_ICON , IM_SN_BG}, {R_ICON , IM_SN_BG}},\
  /*{ {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER, C_BLUE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },*/ \
  /*RSI_SN_PREVIEW_TV_WIN*/\
  { {R_ICON, IM_SN_TVWIN_LEFT}, {R_ICON, IM_SN_TVWIN_MT}, {R_ICON, IM_SN_TVWIN_RIGHT}, {R_ICON, IM_SN_TVWIN_MB}, {R_FILL_RECT_TO_VERTEX, C_TRANS}, {R_ICON, IM_SN_TVWIN_LT}, {R_ICON, IM_SN_TVWIN_RT}, {R_ICON, IM_SN_TVWIN_RB}, {R_ICON, IM_SN_TVWIN_LB}},\
  /*RSI_SN_ADVERTISEMENT_WIN*/\
  { {R_ICON, IM_SN_ADWIN_LEFT}, {R_ICON, IM_SN_ADWIN_MT}, {R_ICON, IM_SN_ADWIN_RIGHT}, {R_ICON, IM_SN_ADWIN_MB}, {R_ICON, IM_SN_AD_PIC}, {R_ICON, IM_SN_ADWIN_LT}, {R_ICON, IM_SN_ADWIN_RT}, {R_ICON, IM_SN_ADWIN_RB}, {R_ICON, IM_SN_ADWIN_LB}},\
  /*RSI_ICON_CHANNEL */\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_PROGRAM},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /* RSI_MENU_ICON*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_PROGRAM_GUID},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_MSG_ICON,*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_EMAIL},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_MANAGER_ICON*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_PROGRAM_MANAGER},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_BOOK_ICON*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_PROGRAM_BOOK},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SYS_ICON*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_SYSTEM_SET},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_TITLE_BG*/\
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE},{R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_SN_BG_TITLE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_CHLIST_SH*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_BG_BLUE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_CHLIST_HL*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_BG_YELLOW},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_EPG_SH*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_BG_BLUE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_EPG_HL*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_BG_YELLOW},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_CHEDIT_SH*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_BG_BLUE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_CHEDIT_HL*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_BG_YELLOW},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_SYSSET_SH*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_BG_BLUE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_SYSSET_HL*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_BG_YELLOW},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_GAME_SH*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_BG_BLUE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_GAME_HL*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_BG_YELLOW},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_MSG_SH*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_BG_BLUE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_MSG_HL*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON, IM_SN_ICON_M_BG_YELLOW},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_COMM_PBAR_BG*/\
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_SN_SOUND_ARTICLE_MB}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
  /*RSI_SN_COMM_PBAR_MID*/\
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_SN_SOUND_ARTICLE_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
  /*RSI_SN_VOLUME*/\
  { {R_ICON , IM_SN_SOUND_LEFT}, {R_IGNORE}, {R_ICON , IM_SN_SOUND_RIGHT}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_SN_SOUND_MIDDLE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},\
  /*RSI_SN_VOLUME_LABA*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON , IM_SN_SOUND_LABA},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_ICON_LABA*/\
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_ICON , IM_SN_SOUND_LABA_BG},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},\
  /*RSI_SN_HELP_BG2*/\
  { {R_ICON, IM_SN_HELP_BG}, {R_IGNORE}, {R_IGNORE},{R_IGNORE}, {R_ICON, IM_SN_HELP_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE},{R_IGNORE}},\
  /*RSI_DIG_BG*/\
  { {R_ICON,IM_SN_DLG_BG_LEFT},{R_ICON,IM_SN_DLG_BG_MT},{R_ICON,IM_SN_DLG_BG_RIGHT},{R_ICON,IM_SN_DLG_BG_MB},{R_ICON,IM_SN_BG},{R_ICON,IM_SN_DLG_BG_LT},{R_ICON,IM_SN_DLG_BG_RT},{R_ICON,IM_SN_DLG_BG_RB},{R_ICON,IM_SN_DLG_BG_LB},},\
  /* RSI_MIN_PROGRESS_BAR_BG*/\
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_SN_SOUND_STATE_BAR_MID}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
  /*RSI_MIN_COMM_PBAR_MID*/\
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_SN_SOUND_STATE_BAR_BG_MID}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
  /*RSI_SEARCH_BG*/\
  { {R_ICON,IM_SN_DLG_BGP_LT}, {R_IGNORE}, {R_ICON,IM_SN_DLG_BGP_RT}, {R_IGNORE}, {R_ICON,IM_SN_DLG_BGP_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
  /*RSI_EMAI_CONTENT_LT*/\
  { {R_ICON,IM_SN_BAR_BLUE_LT}, {R_IGNORE}, {R_ICON,IM_SN_BAR_BLUE_MT}, {R_IGNORE}, {R_ICON,IM_SN_BAR_BLUE_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},\
  /*RSI_EMAI_CONTENT_RT*/\
  { {R_ICON,IM_SN_BAR_BLUE_MT}, {R_IGNORE}, {R_ICON,IM_SN_BAR_BLUE_RT}, {R_IGNORE}, {R_ICON,IM_SN_BAR_BLUE_MT}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},
  


#endif

