

#define  ZHAOMENG_RSI_DEFINE     SN_RSI_COMM_BG, \
									  SN_RSI_PREVIEW_TV_WIN,\
									  SN_RSI_ADVERTISEMENT_WIN,\
									  SN_RSI_ICON_M_BG_BLUE,\
									  SN_RSI_MAIN_PROGRAM_SH,\
									  SN_RSI_MAIN_PROGRAM_HL

#define ZHAOMENG_RSI_STYKE  \
  /*SN_RSI_COMM_BG*/    \
  {{R_ICON,IM_SN_MAINMENU_BG_LEFT},{R_ICON,IM_SN_MAINMENU_BG_MT},{R_ICON,IM_SN_MAINMENU_BG_RIGHT},{R_ICON,IM_SN_MAINMENU_BG_MB},{R_IGNORE},{R_ICON,IM_SN_MAINMENU_BG_LT},{R_ICON,IM_SN_MAINMENU_BG_RT},{R_ICON,IM_SN_MAINMENU_BG_RB},{R_ICON,IM_SN_MAINMENU_BG_LB}},  \
  /*SN_RSI_PREVIEW_TV_WIN*/ \
  {{R_ICON, IM_SN_TVWIN_LEFT}, {R_ICON, IM_SN_TVWIN_MT}, {R_ICON, IM_SN_TVWIN_RIGHT}, {R_ICON, IM_SN_TVWIN_MB}, {R_FILL_RECT_TO_VERTEX, C_TRANS}, {R_ICON, IM_SN_TVWIN_LT}, {R_ICON, IM_SN_TVWIN_RT}, {R_ICON, IM_SN_TVWIN_RB}, {R_ICON, IM_SN_TVWIN_LB}},\
  /*SN_RSI_ADVERTISEMENT_WIN*/  \
  {{R_ICON, IM_SN_ADWIN_LEFT}, {R_ICON, IM_SN_ADWIN_MT}, {R_ICON, IM_SN_ADWIN_RIGHT}, {R_ICON, IM_SN_ADWIN_MB}, {R_FILL_RECT_TO_VERTEX, C_TRANS}, {R_ICON, IM_SN_ADWIN_LT}, {R_ICON, IM_SN_ADWIN_RT}, {R_ICON, IM_SN_ADWIN_RB}, {R_ICON, IM_SN_ADWIN_LB}},\
  /*SN_RSI_ICON_M_BG_BLUE */ \
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_ICON , IM_SN_ICON_M_BG_BLUE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE},{R_IGNORE}},\
  /* SN_RSI_MAIN_PROGRAM_SH*/ \
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE},{R_ICON,IM_SN_ICON_M_BG_BLUE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},\
  /*RSI_MAIN_CHLIST_HL,*/ \
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_ICON,IM_SN_ICON_M_BG_YELLOW}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE},{R_IGNORE}},

