#ifndef __AP_OTA_MONITOR_H__
#define __AP_OTA_MONITOR_H__

#define OTA_MONITOR_DSI_TMOUT 200

#define OTA_MONITOR_PID1 (0x1B58)
#define OTA_MONITOR_DEF_FREQ1_XIONGMAO (267000)
#define OTA_MONITOR_DEF_FREQ1_JINGHUICHENG_QZ (427000)
#define OTA_MONITOR_DEF_SYM1  (6875)

#define OTA_MONITOR_PID2 (0x1B58)
#define OTA_MONITOR_DEF_FREQ2 (411000)
#define OTA_MONITOR_DEF_SYM2  (6875)


typedef enum
{
  OTA_MON_SM_IDLE = 0,
  OTA_MON_SM_CHECK_MAIN_FREQ1,
  OTA_MON_SM_CHECK_MAIN_FREQ2,
  OTA_MON_SM_MAIN_FREQ_WAIT_DSI1,
  OTA_MON_SM_MAIN_FREQ_WAIT_DSI2,
  OTA_MON_SM_WAIT_LOCK1,
  OTA_MON_SM_WAIT_LOCK2,
} ota_mon_sm_t;

typedef enum
{
  OTA_MON_CMD_MONITOR_START = 0,
  OTA_MON_CMD_MONITOR_CHECK_MAIN_FREQ = 0,
} ota_mon_cmd_t;

typedef enum
{
  OTA_MON_EVT_FORCE_OTA = ((APP_RESERVED1<< 16)|ASYNC_EVT),
  OTA_MON_EVT_MAIN_FREQ_FORCE_OTA,
  OTA_MON_EVT_MAIN_FREQ_TMOUT,
} ota_mon_evt_t;

app_t* construct_ap_ota_monitor();

#endif

