
#ifndef _RSC_TOOL_IMAGE_H_
#define _RSC_TOOL_IMAGE_H_

#define IM_SN_ADWIN_LB                                     1 
#define IM_SN_ADWIN_LEFT                                   2 
#define IM_SN_ADWIN_LT                                     3 
#define IM_SN_ADWIN_MB                                     4 
#define IM_SN_ADWIN_MT                                     5 
#define IM_SN_ADWIN_RB                                     6 
#define IM_SN_ADWIN_RIGHT                                  7 
#define IM_SN_ADWIN_RT                                     8 
#define IM_SN_AD_PIC                                       9 
#define IM_SN_BAR_BLUE_LT                                 10 
#define IM_SN_BAR_BLUE_MT                                 11 
#define IM_SN_BAR_BLUE_RIGHT                              12 
#define IM_SN_BAR_BLUE_RT                                 13 
#define IM_SN_BAR_LITTLE_LT                               14 
#define IM_SN_BAR_LITTLE_MT                               15 
#define IM_SN_BAR_LITTLE_RT                               16 
#define IM_SN_BAR_YELLOW_LT                               17 
#define IM_SN_BAR_YELLOW_MT                               18 
#define IM_SN_BAR_YELLOW_RT                               19 
#define IM_SN_BG                                          20 
#define IM_SN_BG_TITLE                                    21 
#define IM_SN_BUTTON_SET_BLUE_LT                          22 
#define IM_SN_BUTTON_SET_BLUE_MT                          23 
#define IM_SN_BUTTON_SET_BLUE_RT                          24 
#define IM_SN_BUTTON_SET_YELLOW_LT                        25 
#define IM_SN_BUTTON_SET_YELLOW_MT                        26 
#define IM_SN_BUTTON_SET_YELLOW_RT                        27 
#define IM_SN_DLG_BGP_LT                                  28 
#define IM_SN_DLG_BGP_MT                                  29 
#define IM_SN_DLG_BGP_RT                                  30 
#define IM_SN_DLG_BG_LB                                   31 
#define IM_SN_DLG_BG_LEFT                                 32 
#define IM_SN_DLG_BG_LT                                   33 
#define IM_SN_DLG_BG_MB                                   34 
#define IM_SN_DLG_BG_MT                                   35 
#define IM_SN_DLG_BG_RB                                   36 
#define IM_SN_DLG_BG_RIGHT                                37 
#define IM_SN_DLG_BG_RT                                   38 
#define IM_SN_EDIT_BG_HL_LT                               39 
#define IM_SN_EDIT_BG_HL_MT                               40 
#define IM_SN_EDIT_BG_HL_RT                               41 
#define IM_SN_EDIT_BG_LT                                  42 
#define IM_SN_EDIT_BG_MT                                  43 
#define IM_SN_EDIT_BG_RT                                  44 
#define IM_SN_EMAIL_CONTENT_BG                            45 
#define IM_SN_EMAIL_CONTENT_BG_LB                         46 
#define IM_SN_EMAIL_CONTENT_BG_LT                         47 
#define IM_SN_EMAIL_CONTENT_BG_MB                         48 
#define IM_SN_EMAIL_CONTENT_BG_ML                         49 
#define IM_SN_EMAIL_CONTENT_BG_MR                         50 
#define IM_SN_EMAIL_CONTENT_BG_MT                         51 
#define IM_SN_EMAIL_CONTENT_BG_RB                         52 
#define IM_SN_EMAIL_CONTENT_BG_RT                         53 
#define IM_SN_EMAIL_DOWN                                  54 
#define IM_SN_EMAIL_LEFT                                  55 
#define IM_SN_EMAIL_LEFT_DOWN                             56 
#define IM_SN_EMAIL_LEFT_TOP                              57 
#define IM_SN_EMAIL_M                                     58 
#define IM_SN_EMAIL_RIGHT                                 59 
#define IM_SN_EMAIL_RIGHT_DOWN                            60 
#define IM_SN_EMAIL_RIGHT_TOP                             61 
#define IM_SN_EMAIL_TOP                                   62 
#define IM_SN_F1                                          63 
#define IM_SN_F2                                          64 
#define IM_SN_F3                                          65 
#define IM_SN_F4                                          66 
#define IM_SN_HELP_BG                                     67 
#define IM_SN_ICON_ARROW_BAR_LEFT                         68 
#define IM_SN_ICON_ARROW_BAR_M                            69 
#define IM_SN_ICON_ARROW_BAR_RIGHT                        70 
#define IM_SN_ICON_ARROW_DOWN                             71 
#define IM_SN_ICON_ARROW_LEFT                             72 
#define IM_SN_ICON_ARROW_RIGHT                            73 
#define IM_SN_ICON_ARROW_UP                               74 
#define IM_SN_ICON_BRACKET_LEFT                           75 
#define IM_SN_ICON_BRACKET_RIGHT                          76 
#define IM_SN_ICON_CAINFO                                 77 
#define IM_SN_ICON_DELETE                                 78 
#define IM_SN_ICON_LANGUAGE                               79 
#define IM_SN_ICON_LOCK                                   80 
#define IM_SN_ICON_LOVE                                   81 
#define IM_SN_ICON_MAIL_NEW                               82 
#define IM_SN_ICON_MAIL_READED                            83 
#define IM_SN_ICON_MOVE                                   84 
#define IM_SN_ICON_MUTE                                   85 
#define IM_SN_ICON_M_BG_BLUE                              86 
#define IM_SN_ICON_M_BG_BLUE1                             87 
#define IM_SN_ICON_M_BG_YELLOW                            88 
#define IM_SN_ICON_M_BG_YELLOW1                           89 
#define IM_SN_ICON_M_EMAIL                                90 
#define IM_SN_ICON_M_PROGRAM                              91 
#define IM_SN_ICON_M_PROGRAM_BOOK                         92 
#define IM_SN_ICON_M_PROGRAM_GUID                         93 
#define IM_SN_ICON_M_PROGRAM_MANAGER                      94 
#define IM_SN_ICON_M_SYSTEM_SET                           95 
#define IM_SN_ICON_PAUSE                                  96 
#define IM_SN_ICON_PROGINFO                               97 
#define IM_SN_ICON_SEARCH                                 98 
#define IM_SN_ICON_SETTING                                99 
#define IM_SN_ICON_SIGNAL_QUA_BG                         100 
#define IM_SN_ICON_SIGNAL_STR_BG                         101 
#define IM_SN_ICON_START_PAUSE                           102 
#define IM_SN_ICON_SYSINFO                               103 
#define IM_SN_ICON_TIME                                  104 
#define IM_SN_ICON_VIEW                                  105 
#define IM_SN_ICON_VIEW_TRACK                            106 
#define IM_SN_ICON_WARNING_2                             107 
#define IM_SN_LINE_H                                     108 
#define IM_SN_LINE_V                                     109 
#define IM_SN_OK_BTN_FOCUS_LT                            110 
#define IM_SN_OK_BTN_FOCUS_MT                            111 
#define IM_SN_OK_BTN_FOCUS_RT                            112 
#define IM_SN_OK_BTN_SHOW_LT                             113 
#define IM_SN_OK_BTN_SHOW_MT                             114 
#define IM_SN_OK_BTN_SHOW_RT                             115 
#define IM_SN_PROGRAM_BG_L                               116 
#define IM_SN_PROGRAM_BG_M                               117 
#define IM_SN_PROGRAM_BG_R                               118 
#define IM_SN_PROGRAM_L                                  119 
#define IM_SN_PROGRAM_M                                  120 
#define IM_SN_PROGRAM_R                                  121 
#define IM_SN_SCREEN_EMAIL                               122 
#define IM_SN_SOUND_ARTICLE_LT                           123 
#define IM_SN_SOUND_ARTICLE_MB                           124 
#define IM_SN_SOUND_ARTICLE_MT                           125 
#define IM_SN_SOUND_ARTICLE_RT                           126 
#define IM_SN_SOUND_LABA                                 127 
#define IM_SN_SOUND_LABA_BG                              128 
#define IM_SN_SOUND_LEFT                                 129 
#define IM_SN_SOUND_MIDDLE                               130 
#define IM_SN_SOUND_RIGHT                                131 
#define IM_SN_SOUND_STATE_BAR_BG_MID                     132 
#define IM_SN_SOUND_STATE_BAR_MID                        133 
#define IM_SN_TVWIN_LB                                   134 
#define IM_SN_TVWIN_LEFT                                 135 
#define IM_SN_TVWIN_LT                                   136 
#define IM_SN_TVWIN_MB                                   137 
#define IM_SN_TVWIN_MT                                   138 
#define IM_SN_TVWIN_RB                                   139 
#define IM_SN_TVWIN_RIGHT                                140 
#define IM_SN_TVWIN_RT                                   141 

#endif
