
#ifndef _RSC_TOOL_STRING_ID_H_
#define _RSC_TOOL_STRING_ID_H_

#define IDS_16_YEARS                                       1 
#define IDS_169                                            2 
#define IDS_1PLAYER                                        3 
#define IDS_2PLAYER                                        4 
#define IDS_4_YEARS                                        5 
#define IDS_43                                             6 
#define IDS_6_YEARS                                        7 
#define IDS_8_YEARS                                        8 
#define IDS_A                                              9 
#define IDS_ACCREDIT_INFO                                 10 
#define IDS_ACCREDIT_PRODUCK_INFO                         11 
#define IDS_ADVANCED_SET                                  12 
#define IDS_ALL                                           13 
#define IDS_AMUSE                                         14 
#define IDS_ANTI_AUTHORIZE                                15 
#define IDS_AREA_ERROR                                    16 
#define IDS_ART                                           17 
#define IDS_ASK_FOR_EXIT_SCAN                             18 
#define IDS_ASK_FOR_STANDBY                               19 
#define IDS_AUDIO_PID                                     20 
#define IDS_AUDIO_SET                                     21 
#define IDS_AUDIO_TRACK                                   22 
#define IDS_AUTHORIZE_DEADLINE                            23 
#define IDS_AUTO                                          24 
#define IDS_AUTO_IP                                       25 
#define IDS_AUTO_SEARCH                                   26 
#define IDS_B2I_SER                                       27 
#define IDS_B2I_VERSION                                   28 
#define IDS_BACK                                          29 
#define IDS_BASIC_SET                                     30 
#define IDS_BAT_TIMEOUT                                   31 
#define IDS_BER                                           32 
#define IDS_BLACK_CHESS                                   33 
#define IDS_BOOK                                          34 
#define IDS_BOOK_ABLE                                     35 
#define IDS_BOOK_ARRIVE_TIP                               36 
#define IDS_BOOK_CONFLICT                                 37 
#define IDS_BOOK_CONFLICT_REPLACE                         38 
#define IDS_BOOK_CONFLICT2                                39 
#define IDS_BOOK_FULL                                     40 
#define IDS_BOOK_IS_FULL                                  41 
#define IDS_BOOK_MANAGE                                   42 
#define IDS_BOOK_REMIND                                   43 
#define IDS_BOOK_REMIND_CONT1                             44 
#define IDS_BOOK_REMIND_CONT2                             45 
#define IDS_BOOK_SET                                      46 
#define IDS_BOTH                                          47 
#define IDS_BOTH_DRAW                                     48 
#define IDS_BOUQUET_SWITCH                                49 
#define IDS_BRIGHT_SET                                    50 
#define IDS_BROADCAST_STATE                               51 
#define IDS_BROADCAST_TIME                                52 
#define IDS_BROWSER                                       53 
#define IDS_BUY_PROGRAM                                   54 
#define IDS_BW_CHESS                                      55 
#define IDS_CA_BASIC_SET                                  56 
#define IDS_CA_CARD_INFO                                  57 
#define IDS_CA_INFO                                       58 
#define IDS_CA_INFO2                                      59 
#define IDS_CA_MONTH                                      60 
#define IDS_CA_NUMBER                                     61 
#define IDS_CA_STATUS                                     62 
#define IDS_CA_VER                                        63 
#define IDS_CA_VER2                                       64 
#define IDS_CA_VERSION                                    65 
#define IDS_CALENDAR                                      66 
#define IDS_CALIB_VERSION                                 67 
#define IDS_CANCEL                                        68 
#define IDS_CANCEL_QUIT                                   69 
#define IDS_CANNOT_PUT_HEARE                              70 
#define IDS_CARD_LOCKED                                   71 
#define IDS_CARD_MANAGE                                   72 
#define IDS_CARD_NUMBER                                   73 
#define IDS_CARD_NUMBER2                                  74 
#define IDS_CARD_OUT                                      75 
#define IDS_CARD_PAIR                                     76 
#define IDS_CARD_PASSWORD_SET                             77 
#define IDS_CARD_STATE                                    78 
#define IDS_CARD_TYPE                                     79 
#define IDS_CAS_VERSION                                   80 
#define IDS_CAT_TIMEOUT                                   81 
#define IDS_CATIP_DLG                                     82 
#define IDS_CHANGE_PASSWORD_TIP                           83 
#define IDS_CHANNEL                                       84 
#define IDS_CHANNEL_CHECK                                 85 
#define IDS_CHANNEL_CLASSIFY                              86 
#define IDS_CHANNEL_EDIT                                  87 
#define IDS_CHANNEL_GUIDE                                 88 
#define IDS_CHANNEL_INFORMATION                           89 
#define IDS_CHANNEL_LIST                                  90 
#define IDS_CHANNEL_NAME                                  91 
#define IDS_CHANNEL_NOT_EXIST                             92 
#define IDS_CHANNEL_NUM_OVERFLOW                          93 
#define IDS_CHANNEL_PROPERTY                              94 
#define IDS_CHANNEL2                                      95 
#define IDS_CHECK                                         96 
#define IDS_CHECK_PASSWORD                                97 
#define IDS_CHESS_COUNT                                   98 
#define IDS_CHILD                                         99 
#define IDS_CHINESE                                      100 
#define IDS_CHROMA_SET                                   101 
#define IDS_CLASSIFY                                     102 
#define IDS_COMMON_MAIL                                  103 
#define IDS_COMPUTER_WIN                                 104 
#define IDS_CONDITIAN_BAN                                105 
#define IDS_CONDITIONAL_ACCEPT                           106 
#define IDS_CONFIRM_NEW_PIN                              107 
#define IDS_CONFIRM_TO_RESTORE                           108 
#define IDS_CONFLICT_AND_REPLACE                         109 
#define IDS_CONFLICT_PWD                                 110 
#define IDS_CONSUMED_POINT                               111 
#define IDS_CONTENT_INTRODUCE                            112 
#define IDS_CONTRAST_SET                                 113 
#define IDS_CRC_PTS                                      114 
#define IDS_CREDIT                                       115 
#define IDS_CRYPTED_PROG_INSERT_SMC                      116 
#define IDS_CUR_CARD_STB_ID_LIST                         117 
#define IDS_CUR_CARD_STB_NUM                             118 
#define IDS_CUR_EVENT_IS_PLAYING                         119 
#define IDS_CUR_PROG_INTRO                               120 
#define IDS_CUR_PROG_TIME_ALL                            121 
#define IDS_CUR_STBID                                    122 
#define IDS_CURRENT                                      123 
#define IDS_CURRENT_PROGRAM1                             124 
#define IDS_CURRENT_PROGRAM2                             125 
#define IDS_CURRENT_TIME                                 126 
#define IDS_CVBS                                         127 
#define IDS_DATE                                         128 
#define IDS_DATE_SET                                     129 
#define IDS_DATE_TIME                                    130 
#define IDS_DAY                                          131 
#define IDS_DECRYPTION_FAIL                              132 
#define IDS_DEL_ALL                                      133 
#define IDS_DEL_ALL_MAIL                                 134 
#define IDS_DEL_CURRENT                                  135 
#define IDS_DEL_CURRENT_MAIL                             136 
#define IDS_DELETE                                       137 
#define IDS_DELETE2                                      138 
#define IDS_DEMOD                                        139 
#define IDS_DEMODUL                                      140 
#define IDS_DEMODUL2                                     141 
#define IDS_DEV_NUM                                      142 
#define IDS_DEV_TYPE                                     143 
#define IDS_DISPLAY_SET                                  144 
#define IDS_DNS                                          145 
#define IDS_DONE                                         146 
#define IDS_DOWN                                         147 
#define IDS_DRAW                                         148 
#define IDS_DURATION                                     149 
#define IDS_DWD_DATE                                     150 
#define IDS_DWD_DUR                                      151 
#define IDS_DWD_TIME                                     152 
#define IDS_ECM                                          153 
#define IDS_EMAIL                                        154 
#define IDS_EMM                                          155 
#define IDS_EMM_PID                                      156 
#define IDS_END_TIME                                     157 
#define IDS_ENGLISH                                      158 
#define IDS_ENTER                                        159 
#define IDS_ENTER_FREQ                                   160 
#define IDS_EPG_INFO_HELP1                               161 
#define IDS_EVENT_OVERTIME                               162 
#define IDS_EVT_FINISHED                                 163 
#define IDS_EVT_NOTIFIED                                 164 
#define IDS_EXCUTE                                       165 
#define IDS_EXIT                                         166 
#define IDS_EXIT_GAME                                    167 
#define IDS_EXIT_MOSAIC                                  168 
#define IDS_EXIT_NVOD                                    169 
#define IDS_EXIT_NVOD_MENU                               170 
#define IDS_EXITING_GAME                                 171 
#define IDS_F4_REFRESH                                   172 
#define IDS_FACTORY_SET                                  173 
#define IDS_FAILED_LOCK_MAIN_FREQ                        174 
#define IDS_FAST                                         175 
#define IDS_FAV                                          176 
#define IDS_FAV_LIST                                     177 
#define IDS_FEED                                         178 
#define IDS_FEED_DURATION                                179 
#define IDS_FEED_SUCCESS                                 180 
#define IDS_FEED_TIME_NOT_ARRIVE                         181 
#define IDS_FINISH_SEARCH_TOTAL_FREQ                     182 
#define IDS_FINISHED_AUTO_IP                             183 
#define IDS_FINISHED_MANUAL_IP                           184 
#define IDS_FINISHI_TIME                                 185 
#define IDS_FIVE_CHESS                                   186 
#define IDS_FN_INVALID                                   187 
#define IDS_FN_RESET                                     188 
#define IDS_FN_SELECT                                    189 
#define IDS_FN_SWITCH                                    190 
#define IDS_FORBIT                                       191 
#define IDS_FREQ_KHZ                                     192 
#define IDS_FREQ_SET_DEMODUL                             193 
#define IDS_FREQ_SET_MAIN_FREQ                           194 
#define IDS_FREQ_SET_NVOD                                195 
#define IDS_FREQ_SET_SYMBOL                              196 
#define IDS_FREQ_SET_TV                                  197 
#define IDS_FREQUENCE                                    198 
#define IDS_FREQUENCE_SET                                199 
#define IDS_FREQUENCE2                                   200 
#define IDS_FRI                                          201 
#define IDS_FRIDAY                                       202 
#define IDS_FULL_SEARCH                                  203 
#define IDS_GAME_CLASS                                   204 
#define IDS_GAME_HELP_ACCELERATE                         205 
#define IDS_GAME_HELP_BACK                               206 
#define IDS_GAME_HELP_ENTER_GAME                         207 
#define IDS_GAME_HELP_EXIT                               208 
#define IDS_GAME_HELP_LR_DIRECTION                       209 
#define IDS_GAME_HELP_LR_MOVE                            210 
#define IDS_GAME_HELP_LR_SEL_LEVEL                       211 
#define IDS_GAME_HELP_PAUSE                              212 
#define IDS_GAME_HELP_PD_SWITCH                          213 
#define IDS_GAME_HELP_PLAY_CHESS                         214 
#define IDS_GAME_HELP_PU_SWITCH                          215 
#define IDS_GAME_HELP_QUIT1                              216 
#define IDS_GAME_HELP_QUIT2                              217 
#define IDS_GAME_HELP_REGRET                             218 
#define IDS_GAME_HELP_ROTATION                           219 
#define IDS_GAME_HELP_START_GAME                         220 
#define IDS_GAME_HELP_UD_DIRECTION                       221 
#define IDS_GAME_HELP_UD_MOVE                            222 
#define IDS_GAME_HELP_UD_SEL                             223 
#define IDS_GAME_INN                                     224 
#define IDS_GAME_OVER                                    225 
#define IDS_GAME_SCORE                                   226 
#define IDS_GATEWAY                                      227 
#define IDS_HAO                                          228 
#define IDS_HARD_VER                                     229 
#define IDS_HARD_VER2                                    230 
#define IDS_HAS_UPGRADE_INFO                             231 
#define IDS_HIDE                                         232 
#define IDS_HOBBIES                                      233 
#define IDS_HOUR                                         234 
#define IDS_HW_CODE                                      235 
#define IDS_IC_OLD_PIN                                   236 
#define IDS_ID                                           237 
#define IDS_IMG_PID                                      238 
#define IDS_IMG_SIZE                                     239 
#define IDS_IMPORTANT                                    240 
#define IDS_IMPORTANT_MAIL                               241 
#define IDS_INDEX_NOT_EXIST                              242 
#define IDS_INFORMATION_PLAZA                            243 
#define IDS_INPUT_FREQ                                   244 
#define IDS_INPUT_IC_PWD                                 245 
#define IDS_INPUT_NEW_CHANNEL                            246 
#define IDS_INPUT_NEW_PIN                                247 
#define IDS_INPUT_NEW_PIN2                               248 
#define IDS_INPUT_OLD_PIN2                               249 
#define IDS_INPUT_PASSWORD                               250 
#define IDS_INPUT_PASSWORD_ERROR                         251 
#define IDS_INPUT_PIN                                    252 
#define IDS_INPUT_TIME_WRONG                             253 
#define IDS_INSERT_CARD_TO_FEED                          254 
#define IDS_INSERT_PARENT_CARD                           255 
#define IDS_INSERT_SMC                                   256 
#define IDS_INSIDE_SERIAL                                257 
#define IDS_INTRODUCE                                    258 
#define IDS_IPP_INFO                                     259 
#define IDS_IPPV_BUY                                     260 
#define IDS_IPPV_INFO                                    261 
#define IDS_IPPV_INFO2                                   262 
#define IDS_IPPV_PROG                                    263 
#define IDS_IRD_STATUS                                   264 
#define IDS_KEY_STATUS                                   265 
#define IDS_KEY_SYSID                                    266 
#define IDS_KEY_VERSION                                  267 
#define IDS_LANGUAGE_SET                                 268 
#define IDS_LAST_FEED_TIME                               269 
#define IDS_LATER_PROGRAM                                270 
#define IDS_LEFT                                         271 
#define IDS_LEFT_TRACK                                   272 
#define IDS_LEFTRIGHT                                    273 
#define IDS_LESS_ONE_MIN                                 274 
#define IDS_LEVEL                                        275 
#define IDS_LEVEL_CONTROL_INFO                           276 
#define IDS_LEVEL_TOO_LOW                                277 
#define IDS_LEVEL2                                       278 
#define IDS_LIST_SWITCH                                  279 
#define IDS_LNB_SHORT                                    280 
#define IDS_LOAD_VERSION                                 281 
#define IDS_LOADER_INFO                                  282 
#define IDS_LOADER_INFO2                                 283 
#define IDS_LOADER_VER                                   284 
#define IDS_LOCAL_IP                                     285 
#define IDS_LOCAL_SOFT_VER                               286 
#define IDS_LOCK                                         287 
#define IDS_LOCK_FAILED_FREQ                             288 
#define IDS_LOCK_PROG                                    289 
#define IDS_LOCK_PWD                                     290 
#define IDS_LOCK_PWD_CONFLICT                            291 
#define IDS_LOCK_PWD_SUCCESS                             292 
#define IDS_LOCK_PWD_WRONG                               293 
#define IDS_LOCKED_INPUT                                 294 
#define IDS_LOOK                                         295 
#define IDS_LOST                                         296 
#define IDS_LOVE                                         297 
#define IDS_LR_SELECT_SP                                 298 
#define IDS_MAIL_CONTENT                                 299 
#define IDS_MAIL_COUNT                                   300 
#define IDS_MAIL_INFO                                    301 
#define IDS_MAIN_FREQ                                    302 
#define IDS_MAINMENU                                     303 
#define IDS_MAN_CODE                                     304 
#define IDS_MANUAL_OTA_TIP                               305 
#define IDS_MANUAL_SEARCH                                306 
#define IDS_MANUAL_UPGRADE                               307 
#define IDS_MANUL_SEARCHING                              308 
#define IDS_MANUL_UPGRADE_FREQ                           309 
#define IDS_MANUL_UPGRADE_MODUL                          310 
#define IDS_MANUL_UPGRADE_SYMBOL                         311 
#define IDS_MEMAIL                                       312 
#define IDS_MENU_DLG                                     313 
#define IDS_MENU_SET                                     314 
#define IDS_MODIFY_LEVEL                                 315 
#define IDS_MODULATE                                     316 
#define IDS_MON                                          317 
#define IDS_MONDAY                                       318 
#define IDS_MONTH                                        319 
#define IDS_MOVE                                         320 
#define IDS_MSG_DLG                                      321 
#define IDS_MUSIC                                        322 
#define IDS_N_RADIO                                      323 
#define IDS_N_TV                                         324 
#define IDS_NATION                                       325 
#define IDS_NEED_SMC_STB_PAIR                            326 
#define IDS_NET_SET                                      327 
#define IDS_NET_SIGNAL_CHECK                             328 
#define IDS_NET_TEST                                     329 
#define IDS_NEW                                          330 
#define IDS_NEW_MAIN_FREQ                                331 
#define IDS_NEW_PASSWORD                                 332 
#define IDS_NEW_PWD                                      333 
#define IDS_NEWS                                         334 
#define IDS_NEXT_PROG_INTRO                              335 
#define IDS_NEXT_PROGRAM1                                336 
#define IDS_NEXT_PROGRAM2                                337 
#define IDS_NEXT_START_TIME                              338 
#define IDS_NIT_TIMEOUT                                  339 
#define IDS_NO                                           340 
#define IDS_NO_ENOUGH_MONEY                              341 
#define IDS_NO_ENTITLEMENT                               342 
#define IDS_NO_GROUP_RADIO                               343 
#define IDS_NO_GROUP_TV                                  344 
#define IDS_NO_LIMIT                                     345 
#define IDS_NO_MOSAIC                                    346 
#define IDS_NO_NVOD                                      347 
#define IDS_NO_PROG                                      348 
#define IDS_NO_PROG_EVENT_LIST                           349 
#define IDS_NO_PROG_FOUND                                350 
#define IDS_NO_PROG_TO_SEARCH                            351 
#define IDS_NO_RADIO_PROG                                352 
#define IDS_NO_SP                                        353 
#define IDS_NO_SP_IN_SMC                                 354 
#define IDS_NO_TELETEXT                                  355 
#define IDS_NO_TV_PROG                                   356 
#define IDS_NOT_EXIST_IN_BOUQUET                         357 
#define IDS_NOT_LIVE_NOW                                 358 
#define IDS_NOW_MAIN_FREQ                                359 
#define IDS_NTSC                                         360 
#define IDS_NUMBER                                       361 
#define IDS_NVOD                                         362 
#define IDS_NVOD_IS_PLAYING                              363 
#define IDS_NVOD_NOT_PLAYING                             364 
#define IDS_NVOD_PLAY_PROGRESS                           365 
#define IDS_NVOD_STATE                                   366 
#define IDS_NVOD2                                        367 
#define IDS_OK                                           368 
#define IDS_OK_SELECT_CHANNEL                            369 
#define IDS_OK_WF                                        370 
#define IDS_OLD_PASSWORD                                 371 
#define IDS_OLD_PWD                                      372 
#define IDS_ONE_MIN_LEFT                                 373 
#define IDS_ONOFF                                        374 
#define IDS_OTHER                                        375 
#define IDS_OUT_OF_DATE                                  376 
#define IDS_OUT_OF_RANGE                                 377 
#define IDS_OUT_OF_WORKTIME                              378 
#define IDS_OUTPUT                                       379 
#define IDS_OUTSIDE_SERAIL                               380 
#define IDS_OVERDUE                                      381 
#define IDS_OVERDUE_TIME                                 382 
#define IDS_PAGEUP                                       383 
#define IDS_PAIR_COMPLETE                                384 
#define IDS_PAIR_OVERTIME                                385 
#define IDS_PAIR_START                                   386 
#define IDS_PAIR_STATE                                   387 
#define IDS_PAL                                          388 
#define IDS_PANNEL_DLG                                   389 
#define IDS_PARAME_SET                                   390 
#define IDS_PARAMETER                                    391 
#define IDS_PARENT_CONTROL                               392 
#define IDS_PASSWORD_CHANGE                              393 
#define IDS_PASSWORD_CONFLICT                            394 
#define IDS_PASSWORD_ERROR                               395 
#define IDS_PASSWORD_MODIFY_SUCCESS                      396 
#define IDS_PASSWORD_SET                                 397 
#define IDS_PASSWORD_SIX_DIGIT                           398 
#define IDS_PAT_TIMEOUT                                  399 
#define IDS_PAUSE                                        400 
#define IDS_PAY_DURATION                                 401 
#define IDS_PERMIT                                       402 
#define IDS_PID                                          403 
#define IDS_PIN_MODIFY                                   404 
#define IDS_PLAT_ID                                      405 
#define IDS_PLAY                                         406 
#define IDS_PLAY_BOOK                                    407 
#define IDS_PLAY_FULLSCR                                 408 
#define IDS_PLAY_PROG_OR_NOT                             409 
#define IDS_PLAY_TIME                                    410 
#define IDS_PLAYER                                       411 
#define IDS_PLAYER_WIN                                   412 
#define IDS_PLAYER1                                      413 
#define IDS_PLAYER1_WIN                                  414 
#define IDS_PLAYER2                                      415 
#define IDS_PLAYER2_WIN                                  416 
#define IDS_PLEASE_WAIT                                  417 
#define IDS_PLS_INPUT_6_PIN                              418 
#define IDS_PLS_INPUT_PIN                                419 
#define IDS_PLS_SELECT_LEVEL                             420 
#define IDS_PMT_TIMEOUT                                  421 
#define IDS_PN_SET                                       422 
#define IDS_POSWER_PWD_SUCCESS                           423 
#define IDS_PRESS_OK_TO_FEED                             424 
#define IDS_PRESS_OK_TO_PAIR                             425 
#define IDS_PRICE                                        426 
#define IDS_PRICE_A                                      427 
#define IDS_PRICE_B                                      428 
#define IDS_PRICE_PER_MIN                                429 
#define IDS_PRICE_PER_PROG                               430 
#define IDS_PRICE_SELECT                                 431 
#define IDS_PRICE2                                       432 
#define IDS_PRJ_SELECT                                   433 
#define IDS_PRO_INFO_NAME                                434 
#define IDS_PRO_INFO_SEVER_ID                            435 
#define IDS_PRO_INFO_SINGAL_STREN                        436 
#define IDS_PRO_INFO_SNR                                 437 
#define IDS_PRO_SEARCH                                   438 
#define IDS_PRODUCT_ID                                   439 
#define IDS_PRODUCT_INFO                                 440 
#define IDS_PRODUCT_NAME                                 441 
#define IDS_PROG_CLASSIFY                                442 
#define IDS_PROG_ID                                      443 
#define IDS_PROG_SP                                      444 
#define IDS_PROG_SP1                                     445 
#define IDS_PROG_SP2                                     446 
#define IDS_PROG_SP3                                     447 
#define IDS_PROG_SP4                                     448 
#define IDS_PROG_UPDATE                                  449 
#define IDS_PROG_UPDATE_TO_SEARCH                        450 
#define IDS_PROGRAM                                      451 
#define IDS_PROGRAM_BOOK                                 452 
#define IDS_PROGRAM_CLASSIFY                             453 
#define IDS_PROGRAM_DELETED                              454 
#define IDS_PROGRAM_GUIDE                                455 
#define IDS_PROGRAM_ID                                   456 
#define IDS_PROGRAM_LOCK                                 457 
#define IDS_PROGRAM_MANAGE                               458 
#define IDS_PROGRAM_NAME                                 459 
#define IDS_PROGRAM_NAME2                                460 
#define IDS_PROGRAM_NAVIGATE                             461 
#define IDS_PROGRAM_NUMBER                               462 
#define IDS_PROGRAM_OVERDUE                              463 
#define IDS_PROGRAM_SEARCH                               464 
#define IDS_PROGRESS                                     465 
#define IDS_PROJECT                                      466 
#define IDS_PROMPT_INFO                                  467 
#define IDS_PWD_MODIFY                                   468 
#define IDS_PWD_ONOFF                                    469 
#define IDS_QAM128                                       470 
#define IDS_QAM16                                        471 
#define IDS_QAM256                                       472 
#define IDS_QAM32                                        473 
#define IDS_QAM64                                        474 
#define IDS_QPSK_HP                                      475 
#define IDS_QPSK_VP                                      476 
#define IDS_QUIT                                         477 
#define IDS_RADIO                                        478 
#define IDS_RATION                                       479 
#define IDS_RDM_NUMBER                                   480 
#define IDS_READ                                         481 
#define IDS_READING_WAITE                                482 
#define IDS_RECIEVING_DATA                               483 
#define IDS_RECIEVING_EPG                                484 
#define IDS_RECIEVING_MOSAIC                             485 
#define IDS_RECORD                                       486 
#define IDS_RECORDABLE                                   487 
#define IDS_RECORDED                                     488 
#define IDS_RELEASE_TIME                                 489 
#define IDS_REMAIN_CAPACITY                              490 
#define IDS_REORDER                                      491 
#define IDS_RESET                                        492 
#define IDS_RESET_FACTORY                                493 
#define IDS_RESETING_FACTORY                             494 
#define IDS_RESETING_FINISHED                            495 
#define IDS_RESETING_WAIT                                496 
#define IDS_RESTORE_FACTORY                              497 
#define IDS_RESTORE_FACTORY_INTRODUCE                    498 
#define IDS_RESTORE_FACTORYING                           499 
#define IDS_RGB                                          500 
#define IDS_RIGHT                                        501 
#define IDS_RIGHT_TRACK                                  502 
#define IDS_SAT                                          503 
#define IDS_SATDAY                                       504 
#define IDS_SAVE                                         505 
#define IDS_SAVE_DATA                                    506 
#define IDS_SAVE_DATA_FAILED                             507 
#define IDS_SAVE_DATA_SUCCESS                            508 
#define IDS_SAVE_FAILED                                  509 
#define IDS_SAVE_MODIFY                                  510 
#define IDS_SAVE_QUIT                                    511 
#define IDS_SAVE_SET                                     512 
#define IDS_SAVE_SUCCESS                                 513 
#define IDS_SAVING                                       514 
#define IDS_SAVING_OR_NOT                                515 
#define IDS_SAVING_WAITE                                 516 
#define IDS_SCIENCE                                      517 
#define IDS_SCORE                                        518 
#define IDS_SDT_TIMEOUT                                  519 
#define IDS_SEARCH                                       520 
#define IDS_SEARCH_FINISHED                              521 
#define IDS_SEARCH_IS_END                                522 
#define IDS_SEARCH_PATTERN                               523 
#define IDS_SEARCH_RADIO_PROG                            524 
#define IDS_SEARCH_RESULTS                               525 
#define IDS_SEARCH_TV_PROG                               526 
#define IDS_SEARCHING                                    527 
#define IDS_SEARCHING_FREQ                               528 
#define IDS_SEARCHING_TO_EXIST                           529 
#define IDS_SEARCHING_WAITE                              530 
#define IDS_SELCET_PARAMETER                             531 
#define IDS_SELECT                                       532 
#define IDS_SELECT_CHANNEL                               533 
#define IDS_SELECT_FINISH_TIME                           534 
#define IDS_SELECT_MONTH                                 535 
#define IDS_SELECT_PRJ                                   536 
#define IDS_SELECT_SP                                    537 
#define IDS_SELECT_START_TIME                            538 
#define IDS_SELECT_WEEK                                  539 
#define IDS_SELECT_YEAR                                  540 
#define IDS_SELECT2                                      541 
#define IDS_SELECTED                                     542 
#define IDS_SENDER                                       543 
#define IDS_SEQUENCE                                     544 
#define IDS_SER_NUMBER                                   545 
#define IDS_SERVICE_ID                                   546 
#define IDS_SERVICE_INFO                                 547 
#define IDS_SERVICE_LIST                                 548 
#define IDS_SERVICE_STATUS                               549 
#define IDS_SERVICE_SWITCH                               550 
#define IDS_SET                                          551 
#define IDS_SET_PASSWORD                                 552 
#define IDS_SET_SUCCESS                                  553 
#define IDS_SHOW_CHANNEL                                 554 
#define IDS_SIG_DATE                                     555 
#define IDS_SIG_TIME                                     556 
#define IDS_SIG_VERSION                                  557 
#define IDS_SIGNAL_CHECK                                 558 
#define IDS_SKIP_CURRENT_FREQ                            559 
#define IDS_SLEEP_TURN_OFF                               560 
#define IDS_SLOT                                         561 
#define IDS_SLOT_ID                                      562 
#define IDS_SLOT_ID2                                     563 
#define IDS_SLOT_INFO                                    564 
#define IDS_SLOT_POINT                                   565 
#define IDS_SMART_CARD_NUMBER                            566 
#define IDS_SMART_CARD_NUMBER2                           567 
#define IDS_SMARTCARD_INFO                               568 
#define IDS_SMC_OVERDUE                                  569 
#define IDS_SMC_UNPAIRED                                 570 
#define IDS_SNAKE                                        571 
#define IDS_SNR                                          572 
#define IDS_SOCIAL                                       573 
#define IDS_SOFT_VER                                     574 
#define IDS_SOFT_VER2                                    575 
#define IDS_SOFTWARE_UPGRADE                             576 
#define IDS_SOUND_CONTROL                                577 
#define IDS_SP                                           578 
#define IDS_SP_ID                                        579 
#define IDS_SP_ID2                                       580 
#define IDS_SP_INFO                                      581 
#define IDS_SP_NAME                                      582 
#define IDS_SP_NUM                                       583 
#define IDS_SP_OPERATOR_INFO                             584 
#define IDS_SPACE_IS_FULL                                585 
#define IDS_SPECIFY_FREQ                                 586 
#define IDS_SPEED                                        587 
#define IDS_SPORT                                        588 
#define IDS_SQE_NUMBER                                   589 
#define IDS_START_PWD                                    590 
#define IDS_START_SEARCH                                 591 
#define IDS_START_SEARCH_FAILED                          592 
#define IDS_START_TIME                                   593 
#define IDS_START_TIME2                                  594 
#define IDS_START_TIME3                                  595 
#define IDS_STATE                                        596 
#define IDS_STATUS                                       597 
#define IDS_STB_CARD_PAIR                                598 
#define IDS_STB_INFO                                     599 
#define IDS_STB_PAIR                                     600 
#define IDS_STB_PAIR_INFO                                601 
#define IDS_STB_VERSION                                  602 
#define IDS_STERO                                        603 
#define IDS_STOCK_ANALYZE                                604 
#define IDS_STREM                                        605 
#define IDS_STRENGTH                                     606 
#define IDS_SUBNET_MASK                                  607 
#define IDS_SUN                                          608 
#define IDS_SUNDAY                                       609 
#define IDS_SURE                                         610 
#define IDS_SVIDEO                                       611 
#define IDS_SWITCH                                       612 
#define IDS_SWITCH_AREA                                  613 
#define IDS_SWITCH_CHANNEL                               614 
#define IDS_SWITCH_DURATION                              615 
#define IDS_SWITCH_SET                                   616 
#define IDS_SWITCH_TIME                                  617 
#define IDS_SWITCH_WINDOW                                618 
#define IDS_SYMBOL                                       619 
#define IDS_SYMBOL2                                      620 
#define IDS_SYS_INFO_ISSUE_TIME                          621 
#define IDS_SYS_NO_SIGNAL                                622 
#define IDS_SYS_PAIR                                     623 
#define IDS_SYS_UPDATE                                   624 
#define IDS_SYSSET_CACARD_INFO                           625 
#define IDS_SYSTEM_INFO                                  626 
#define IDS_SYSTEM_SET                                   627 
#define IDS_TETRIS                                       628 
#define IDS_THS                                          629 
#define IDS_THURSDAY                                     630 
#define IDS_TIME_SET                                     631 
#define IDS_TIMEZONE                                     632 
#define IDS_TIP_INFO                                     633 
#define IDS_TITLE                                        634 
#define IDS_TODAY                                        635 
#define IDS_TOTAL_CHANNEL_NUM                            636 
#define IDS_TOTAL_FREQ_NUM                               637 
#define IDS_TRACK_CONTROL                                638 
#define IDS_TRACK_GLOBAL                                 639 
#define IDS_TRACK_MODE                                   640 
#define IDS_TRACK_SET                                    641 
#define IDS_TRANSPARENCE_SET                             642 
#define IDS_TUESDAY                                      643 
#define IDS_TUNER                                        644 
#define IDS_TUS                                          645 
#define IDS_TV                                           646 
#define IDS_TV_FILM                                      647 
#define IDS_TV_PROGRAM                                   648 
#define IDS_TV_SIGNAL_CHECK                              649 
#define IDS_TYPE                                         650 
#define IDS_UNIT_KBAUD                                   651 
#define IDS_UNIT_KHZ                                     652 
#define IDS_UNKNOW_SMC                                   653 
#define IDS_UP                                           654 
#define IDS_UPDOWN                                       655 
#define IDS_UPGRADE_PROGRESS                             656 
#define IDS_UPGRADE_SOFT_VER                             657 
#define IDS_UPGRADE_TO_NEW_VER                           658 
#define IDS_USER_NO_ENTITLEMENT                          659 
#define IDS_VARIANT                                      660 
#define IDS_VERIFY_NEW_PIN                               661 
#define IDS_VERIFY_PASSWORD                              662 
#define IDS_VERIFY_PWD                                   663 
#define IDS_VERSION                                      664 
#define IDS_VIDEO_PID                                    665 
#define IDS_VIDEO_SET                                    666 
#define IDS_VIEW_ABLE                                    667 
#define IDS_VOLUME                                       668 
#define IDS_VOLUME_CONTROL                               669 
#define IDS_WATCH_LEVE                                   670 
#define IDS_WED                                          671 
#define IDS_WEDNESDAY                                    672 
#define IDS_WEEK                                         673 
#define IDS_WELCOME_IPPV                                 674 
#define IDS_WHITE_CHESS                                  675 
#define IDS_WIN                                          676 
#define IDS_WOR_DURATION                                 677 
#define IDS_WOR_DURATION_SET                             678 
#define IDS_WRITE_USER_INFO                              679 
#define IDS_WRONG_PWD                                    680 
#define IDS_YEAR                                         681 
#define IDS_YES                                          682 
#define IDS_YOU_LOSE                                     683 
#define IDS_YOU_WIN                                      684 
#define IDS_YPBPR                                        685 
#define IDS_PRO_LIST                                     686 
#define IDS_CA_OPERATOR_ADDRES                           687 
#define IDS_CA_OPERATOR_TEL                              688 
#define IDS_CA_PARAME_SET_ERROR                          689 
#define IDS_CA_PASSWORD_PIN_ERROR                        690 
#define IDS_CA_PASSWORD_PIN_LOCKED                       691 
#define IDS_CA_PASSWORD_PIN_NUMB                         692 
#define IDS_CA_PRICE_UNIT                                693 
#define IDS_CA_PRICE_UNIT_2                              694 
#define IDS_CA_PRICE_UNIT_TEXT                           695 
#define IDS_CA_PRO_WF                                    696 
#define IDS_CA_PROG_HIGH_WATCH_LEVEL                     697 
#define IDS_CA_PROG_OUT_DATE                             698 
#define IDS_CA_PROG_WATCH_LEVEL                          699 
#define IDS_CA_PURSE_BALANCE1                            700 
#define IDS_CA_PURSE_BALANCE2                            701 
#define IDS_CA_PURSE_BALANCE3                            702 
#define IDS_CA_PURSE_BALANCE4                            703 
#define IDS_CA_REPAIR_STB                                704 
#define IDS_CA_SLAVE_NEED_MASTER                         705 
#define IDS_CA_SLAVE_NEED_MASTER_XSD                     706 
#define IDS_CA_SMART_UNLOCK                              707 
#define IDS_CA_SP_ID                                     708 
#define IDS_CA_SP_ID_XSD                                 709 
#define IDS_CA_SP_NAME                                   710 
#define IDS_CA_STB_NO_PAIR                               711 
#define IDS_CA_STB_PAIR                                  712 
#define IDS_CA_SW1SW2_CARD_NOT_INIT                      713 
#define IDS_CA_SW1SW2_CHILD_AUTH_EXPIRED                 714 
#define IDS_CA_SW1SW2_CHILD_AUTH_TIMEOUT                 715 
#define IDS_CA_SW1SW2_CHILD_NOT_AUTHORIZED               716 
#define IDS_CA_SW1SW2_ECM_NOT_AUTHORIZED                 717 
#define IDS_CA_SW1SW2_EXPIRED                            718 
#define IDS_CA_SW1SW2_INCORRECT_SMARTCARD_ID             719 
#define IDS_CA_SW1SW2_LIMIT_AREA                         720 
#define IDS_CA_SW1SW2_LIMIT_CARD                         721 
#define IDS_CA_SW1SW2_NO_CHILD_AUTH                      722 
#define IDS_CA_SW1SW2_NOT_CHILD_MODE                     723 
#define IDS_CA_SW1SW2_NOT_PAIRED                         724 
#define IDS_CA_SW1SW2_PPV_EXCEED                         725 
#define IDS_CA_SW1SW2_STB_SN_NOT_MATCH                   726 
#define IDS_CA_SYS_DESC                                  727 
#define IDS_CA_SYS_ID_ERR                                728 
#define IDS_CA_SYS_MARKER                                729 
#define IDS_CA_SYS_PROVIDER                              730 
#define IDS_CA_TYPE                                      731 
#define IDS_CA_USER_BALANCE                              732 
#define IDS_CAS_ADDRESS                                  733 
#define IDS_CAS_C_CANCEL_PAIRED_OK                       734 
#define IDS_CAS_C_CARD_ZONE_CHECK_ENTER                  735 
#define IDS_CAS_C_CARD_ZONE_CHECK_OK                     736 
#define IDS_CAS_C_CARD_ZONE_INVALID                      737 
#define IDS_CAS_C_MASTERSLAVE_NEEDPAIRED                 738 
#define IDS_CAS_C_MASTERSLAVE_PAIRED_OK                  739 
#define IDS_CAS_C_MASTERSLAVE_PAIRED_UPDATE              740 
#define IDS_CAS_C_USERCDN_LIMIT_CTRL_DISABLE             741 
#define IDS_CAS_C_USERCDN_LIMIT_CTRL_ENABLE              742 
#define IDS_CAS_C_ZONECDN_LIMIT_CTRL_DISABLE             743 
#define IDS_CAS_C_ZONECDN_LIMIT_CTRL_ENABLE              744 
#define IDS_CAS_COMMAND_INVALID                          745 
#define IDS_CAS_E_CARD_ADDR_CTL_CLOSE                    746 
#define IDS_CAS_E_CARD_ADDR_CTL_OPEN                     747 
#define IDS_CAS_E_CARD_CONDITIONAL_LIMIT                 748 
#define IDS_CAS_E_CARD_ENTITLE_EXPIRED                   749 
#define IDS_CAS_E_CARD_ENTITLE_UPDATE                    750 
#define IDS_CAS_E_CARD_INIT                              751 
#define IDS_CAS_E_CARD_IPPV_NO_MONEY                     752 
#define IDS_CAS_E_CARD_IPPV_OUT_TIME                     753 
#define IDS_CAS_E_CARD_NET_ERR_LOCK                      754 
#define IDS_CAS_E_CARD_NET_ERR_UNLOCK                    755 
#define IDS_CAS_E_CARD_SYS_ERR_LOCK                      756 
#define IDS_CAS_E_CARD_SYS_ERR_UNLOCK                    757 
#define IDS_CAS_E_CARD_UPDATE                            758 
#define IDS_CAS_E_CARD_WRITEPURSER_ERROR                 759 
#define IDS_CAS_E_ECM_EMM_RET_UNKNOWN_ERROR              760 
#define IDS_CAS_E_ECM_ERROR                              761 
#define IDS_CAS_E_EMM_ERROR                              762 
#define IDS_CA_VER_WF                                    763 
#define IDS_CA_WALLET_RENEW                              764 
#define IDS_CA_WATCH_ASK                                 765 
#define IDS_CA_WATCH_LEVEL                               766 
#define IDS_CA_WORK_TIME                                 767 
#define IDS_CA_WORK_TIME_ERROR                           768 
#define IDS_CANOT_CHOSE_P_PG                             769 
#define IDS_CARD_COS_VER                                 770 
#define IDS_CAS_E_NEED_STB_PAIR                          771 
#define IDS_CAS_E_NO_ECM_INFO                            772 
#define IDS_CAS_E_PAIRED_OTHERCARD_ERROR                 773 
#define IDS_CAS_E_PAIRED_OTHERSTB_ERROR                  774 
#define IDS_CAS_E_READ_CARD_NUMBER_ERROR                 775 
#define IDS_CAS_E_RET_ECM_DATA_ERROR                     776 
#define IDS_CAS_E_RET_ECM_EMM_P1P2_ERROR                 777 
#define IDS_CAS_E_RET_ECM_EMM_P3_ERROR                   778 
#define IDS_CAS_E_RET_ERROR                              779 
#define IDS_CAS_E_UNKNOWN_ERROR                          780 
#define IDS_CAS_EXPIRATION                               781 
#define IDS_CAS_FORBIDDEN                                782 
#define IDS_CAS_LENGTH                                   783 
#define IDS_CAS_MONEY                                    784 
#define IDS_CAS_OUTOFPERIOD                              785 
#define IDS_CAS_S_STB_CARD_PAIR_SUCCESS                  786 
#define IDS_CAS_UNLICENSED                               787 
#define IDS_CAS_UNMATCHED                                788 
#define IDS_CAS_ZONE_ERR                                 789 
#define IDS_CHARA_CODE                                   790 
#define IDS_CHECK_USER_PIN                               791 
#define IDS_CLOSING_CA_LIB                               792 
#define IDS_CPC_ORDER_TIP                                793 
#define IDS_CUR_CHANNEL_NAME                             794 
#define IDS_CUR_PAGE                                     795 
#define IDS_CUR_PRICE                                    796 
#define IDS_CYCLE_NUM_TO_WATCH                           797 
#define IDS_DAYS                                         798 
#define IDS_DIGIT_NOT_ENOUGH                             799 
#define IDS_DUR_TIME                                     800 
#define IDS_FEED_FAILURE                                 801 
#define IDS_HAS_ORRDERED                                 802 
#define IDS_INPUT_CYC_IS_INVALID                         803 
#define IDS_INVALID_PRICE                                804 
#define IDS_IPP_SELECT                                   805 
#define IDS_IPP_TOTAL                                    806 
#define IDS_IPPV_ORDER                                   807 
#define IDS_IPPV_RESCING                                 808 
#define IDS_LOCKED                                       809 
#define IDS_MAIN_FREQ_SET                                810 
#define IDS_MONTHS                                       811 
#define IDS_MOTHER_CARD_NUM                              812 
#define IDS_NEED_VERIFY_PIN                              813 
#define IDS_NO_IPP_UPPER_MENU                            814 
#define IDS_NOT_ORDER                                    815 
#define IDS_O_S_IPP_PROG                                 816 
#define IDS_OPEN_CLOSE_CA_DEBUG                          817 
#define IDS_OPENING_CA_LIB                               818 
#define IDS_ORDER_PRICE                                  819 
#define IDS_ORDER_SUCCESS                                820 
#define IDS_OTHER_INFO                                   821 
#define IDS_PIN_MODIFY_LOCK                              822 
#define IDS_PIN_STATUS                                   823 
#define IDS_PROG_INFO_CHECK                              824 
#define IDS_PROGRAM_TYPE                                 825 
#define IDS_READ_MOTHER_CARD_FAILURE                     826 
#define IDS_RECEIVED_DATA_FAIL                           827 
#define IDS_RECEIVED_ZONE_TIME                           828 
#define IDS_SECOND                                       829 
#define IDS_SELECTED_STATUS                              830 
#define IDS_SHOW_MAX_MAIL_CNT                            831 
#define IDS_SIGNAL_FREQ_SET                              832 
#define IDS_SMART_CARD_NUMBER_WF                         833 
#define IDS_SON_CARD_TIME                                834 
#define IDS_SON_LEFT_TIME                                835 
#define IDS_STB_CA_MODULE_VER                            836 
#define IDS_STB_SN                                       837 
#define IDS_SUC_P_RACHARGE                               838 
#define IDS_SURE_TO_BUY_PG                               839 
#define IDS_SURE_TO_UNBOOK_PG                            840 
#define IDS_TOTAL_ENTITLED_NUB                           841 
#define IDS_UNLOCKED                                     842 
#define IDS_UNREAD_MAIL_CNT                              843 
#define IDS_UNSU_SUCCESS                                 844 
#define IDS_US_FAIL_TO_RETRY                             845 
#define IDS_WALLET_CHECK                                 846 
#define IDS_WALLET_DONOT_EXIST                           847 
#define IDS_WALLET_LEFT                                  848 
#define IDS_WALLET_USED                                  849 
#define IDS_WATCHED_IPP_PROG                             850 
#define IDS_YEARS                                        851 
#define IDS_ZONE_CODE_STATUS                             852 
#define IDS_NN_PRICE                                     853 
#define IDS_CARD_BECOME_DUE_DF3                          854 
#define IDS_INSERT_CHILD_CARD                            855 
#define IDS_CAS_E_FEED_DATA_ERROR_DF                     856 
#define IDS_E12_DF                                       857 
#define IDS_E14_DF                                       858 
#define IDS_CARD_DUE_ZHECHENG_1                          859 
#define IDS_CARD_DUE_ZHECHENG_2                          860 
#define IDS_READ_MOTHER_CARD_DATA_INFO                   861 
#define IDS_CARD_TYPE_NO_SIGN                            862 
#define IDS_CA_MASTER_CARD_ID_NO_SIGN                    863 
#define IDS_CA_LEVEL10                                   864 
#define IDS_CA_LEVEL11                                   865 
#define IDS_CA_LEVEL12                                   866 
#define IDS_CA_LEVEL13                                   867 
#define IDS_CA_LEVEL14                                   868 
#define IDS_CA_LEVEL15                                   869 
#define IDS_CA_LEVEL16                                   870 
#define IDS_CA_LEVEL17                                   871 
#define IDS_CA_LEVEL18                                   872 
#define IDS_PATCH_TIME                                   873 
#define IDS_PATCH_STATUS                                 874 
#define IDS_CHARACTERS                                   875 
#define IDS_AREA_CODE                                    876 
#define IDS_BOUQUET_ID                                   877 
#define IDS_SYS_NO_SIGNAL_JIZHONG_SHANXI                 878 
#define IDS_AUTO_BROWSE_MODE                             879 
#define IDS_CARD_DUE_ZHECHENG_3                          880 
#define IDS_CARD_DUE_ZHECHENG_4                          881 
#define IDS_HELP_BACK                                    882 
#define IDS_HELP_EXIT                                    883 
#define IDS_DEL_ANNOUNCE                                 884 
#define IDS_ANNOUNCE_INFO                                885 
#define IDS_NAME2                                        886 
#define IDS_RECEIVED                                     887 
#define IDS_REST_SPACE                                   888 
#define IDS_DOT                                          889 
#define IDS_MINUTE                                       890 
#define IDS_IPP_TYPE                                     891 
#define IDS_IPP_PRICE                                    892 
#define IDS_IPP_DISTANCE                                 893 
#define IDS_IPP_INFOR2                                   894 
#define IDS_INPUT_PIN2                                   895 
#define IDS_IPP_HELP                                     896 
#define IDS_FEED_PARAM_ERROR                             897 
#define IDS_FEED_DATA_ERROR                              898 
#define IDS_FEED_PARTNER_FAILED                          899 
#define IDS_FEED_UNKNOW_ERROR                            900 
#define IDS_PIN_ERROR                                    901 
#define IDS_DEL_MAIL                                     902 
#define IDS_VERIFY_ERROR                                 903 
#define IDS_ENTER_NEW_PIN                                904 
#define IDS_CA_MOTHER_CARD                               905 
#define IDS_CA_CHILD_CARD                                906 
#define IDS_CA_NO_ENABLE                                 907 
#define IDS_CA_NO_MONEY                                  908 
#define IDS_CA_NO_NEED_PAIR                              909 
#define IDS_CA_NO_PURCH_PROG                             910 
#define IDS_CA_NOT_CERTIFIED                             911 
#define IDS_CA_NUM                                       912 
#define IDS_CA_CHOOSE_NET                                913 
#define IDS_CA_CUR_PRO_WF                                914 
#define IDS_CA_CUR_TIME                                  915 
#define IDS_CA_DELETE_CARD                               916 
#define IDS_CA_E_APP_RESUME                              917 
#define IDS_CA_E_APP_STOP                                918 
#define IDS_CA_E_CHARGE                                  919 
#define IDS_CA_E_PROG_AUTH                               920 
#define IDS_CA_E_PROG_UNAUTH                             921 
#define IDS_CA_E_UPDATE_GK                               922 
#define IDS_CA_E_UPDATE_GNO                              923 
#define IDS_CA_EMAIL_NO_SPACE                            924 
#define IDS_CA_GROUP_ID                                  925 
#define IDS_CA_ID                                        926 
#define IDS_PARAMETER_ERROR                              927 
#define IDS_CA_CARD_INVALID                              928 
#define IDS_CA_CARD_INVALIDSTB                           929 
#define IDS_CA_CARD_LIMIT                                930 
#define IDS_CA_CARD_LOCK                                 931 
#define IDS_CA_CARD_NEED_UPDATE                          932 
#define IDS_CA_CARD_NO_MONEY                             933 
#define IDS_CA_CARD_NOT_INSERT                           934 
#define IDS_CA_CARD_OVER_DATE                            935 
#define IDS_CA_CARD_PARTNER_FAILED                       936 
#define IDS_CA_CARD_PARTNER_FAILED_XSD                   937 
#define IDS_CA_CARD_REMATCH_CANCEL                       938 
#define IDS_CA_CARD_STATE                                939 
#define IDS_CA_CARD_STOP                                 940 
#define IDS_CA_CARD_UPDATE_ERR                           941 
#define IDS_CA_CARD_VALID_DATE                           942 
#define IDS_CA_CARD_VER                                  943 
#define IDS_CA_CARD_VERSION                              944 
#define IDS_CA_CARD_ZONE_CODE                            945 
#define IDS_CA_CERTIFY_INTERVAL                          946 
#define IDS_CA_CERTIFY_TIME                              947 
#define IDS_CA_CARD_PIN_INVALID                          948 
#define IDS_E00                                          949 
#define IDS_E01                                          950 
#define IDS_E02                                          951 
#define IDS_E03                                          952 
#define IDS_E04                                          953 
#define IDS_E05                                          954 
#define IDS_E06                                          955 
#define IDS_E07                                          956 
#define IDS_E08                                          957 
#define IDS_E09                                          958 
#define IDS_E10                                          959 
#define IDS_E11                                          960 
#define IDS_E12                                          961 
#define IDS_E13                                          962 
#define IDS_E14                                          963 
#define IDS_E15                                          964 
#define IDS_E16                                          965 
#define IDS_E17                                          966 
#define IDS_E18                                          967 
#define IDS_E19                                          968 
#define IDS_E20                                          969 
#define IDS_E21                                          970 
#define IDS_E22                                          971 
#define IDS_E23                                          972 
#define IDS_E24                                          973 
#define IDS_E25                                          974 
#define IDS_E26                                          975 
#define IDS_E27                                          976 
#define IDS_E28                                          977 
#define IDS_E29                                          978 
#define IDS_E30                                          979 
#define IDS_E31                                          980 
#define IDS_E32                                          981 
#define IDS_E33                                          982 
#define IDS_E34                                          983 
#define IDS_E35                                          984 
#define IDS_E42                                          985 
#define IDS_CA_FEED_NULL                                 986 
#define IDS_CARD_BECOME_DUE                              987 
#define IDS_CARD_VERSION                                 988 
#define IDS_CARD_PCVISITION                              989 
#define IDS_RATING                                       990 
#define IDS_RATE_CONTROL                                 991 
#define IDS_INPUT_RATE                                   992 
#define IDS_OLD_PIN                                      993 
#define IDS_NEW_PIN                                      994 
#define IDS_AFFIRMABLE_PIN                               995 
#define IDS_MODIFY_PIN                                   996 
#define IDS_SMARTCARD_FEED                               997 
#define IDS_OK_TO_CONTINUE                               998 
#define IDS_CURRENT_IS_MOTHER_CARD                       999 
#define IDS_CURRENT_IS_SON_CARD                         1000 
#define IDS_PLEASE_RESET                                1001 
#define IDS_NEWS_INFO                                   1002 
#define IDS_EPG                                         1003 
#define IDS_PROGRAME_MANAGE                             1004 
#define IDS_INTERACTIVE_TV                              1005 
#define IDS_NOTHIS_FUNCTION                             1006 
#define IDS_UPDATE_NIT_VERSION_NUM                      1007 
#define IDS_UPDATE_SOFTWARE                             1008 
#define IDS_AUTHORIZATION_OK                            1009 
#define IDS_NO_ENTITLE_INFO                             1010 
#define IDS_LIMITED                                     1011 
#define IDS_ENTITLE_CLOSED                              1012 
#define IDS_ENTITLE_PAUSED                              1013 
#define IDS_CHARGE                                      1014 
#define IDS_CONSUME                                     1015 
#define IDS_MANUFACTURER                                1016 
#define IDS_PARAM_ERROR                                 1017 
#define IDS_NVRAM_ERROR                                 1018 
#define IDS_NO_ENOUGH_MEM                               1019 
#define IDS_SPACE_FULL                                  1020 
#define IDS_UNKNOWN_ERROR                               1021 
#define IDS_NOT_SUPPORT                                 1022 
#define IDS_USER_ID                                     1023 
#define IDS_EXPIRY_DATE                                 1024 
#define IDS_IPPV_BURSE                                  1025 
#define IDS_CARD_PAIR_FAILE                             1026 
#define IDS_CARD_STB_PAIR_FAILE                         1027 
#define IDS_SOPAIR_FAILE                                1028 
#define IDS_HELP_CANCEL                                 1029 
#define IDS_CAS_S_ZONE_LOCK                             1030 
#define IDS_YPBPR_CVBS                                  1031 
#define IDS_SVIDEO_CVBS                                 1032 
#define IDS_CARD_AUTH_DUE                               1033 
#define IDS_RECEIVE_TIME                                1034 
#define IDS_CAS_E_CARD_UPG_FAILED                       1035 
#define IDS_CAS_E_CARD_RST_FAIL                         1036 
#define IDS_CAS_E_CADR_NO_MONEY                         1037 
#define IDS_CAS_E_SERVICE_LOCKED                        1038 
#define IDS_CAS_E_CADR_NOT_ACT                          1039 
#define IDS_CAS_E_ZONE_CODE_ERR                         1040 
#define IDS_CAS_E_NOT_RECEIVED_SPID                     1041 
#define IDS_CAS_E_PIN_INVALID                           1042 
#define IDS_CAS_ERROR_CARD_NOTSUPPORT                   1043 
#define IDS_CAS_E_IPP_INFO_ERROR                        1044 
#define IDS_CAS_E_FEED_DATA_ERROR                       1045 
#define IDS_CAS_S_CARD_RST_SUCCESS                      1046 
#define IDS_CAS_S_CARD_UPG_SUCCESS                      1047 
#define IDS_CAS_S_MODIFY_ZONECODE                       1048 
#define IDS_SON_CARD_FEED                               1049 
#define IDS_FEED_INSERT_CHILD_CARD                      1050 
#define IDS_NOT_SUPPORT_FEED                            1051 
#define IDS_PROMPT                                      1052 
#define IDS_GENERAL_PRO                                 1053 
#define IDS_IPPV_PRO_INFO                               1054 
#define IDS_IPP_CONSUME                                 1055 
#define IDS_PRODUCT_ID2                                 1056 
#define IDS_COMMISION_STATE                             1057 
#define IDS_COMMISION_DATE                              1058 
#define IDS_IPP_ID                                      1059 
#define IDS_TYPE2                                       1060 
#define IDS_START_TIME4                                 1061 
#define IDS_END_TIME4                                   1062 
#define IDS_REMAIN_NUMBER                               1063 
#define IDS_GLIDE_NUM                                   1064 
#define IDS_MONEY                                       1065 
#define IDS_CA_MAIN_FREQ_SET                            1066 
#define IDS_CAS_E_IC_CMD_FAIL                           1067 
#define IDS_CA_AUTH_TIME_EDN                            1068 
#define IDS_CA_FORCE_PROG                               1069 
#define IDS_INDEX                                       1070 
#define IDS_TIME                                        1071 
#define IDS_SEL_ALL                                     1072 
#define IDS_SEL_CURRENT                                 1073 
#define IDS_SELECT_SURE                                 1074 

#endif
