/****************************************************************************
* Notice:      Copyright (c) Montage Techonoloy Corporation (2009).
*              All rights reserved.
* Owner:       Kevin Li <kai.li@montage-tech.com>
*              Mark Wu <mark.wu@montage-tech.com>
****************************************************************************/
#ifndef __UI_CONDITIONAL_ACCEPT_MOTHER_H__
#define __UI_CONDITIONAL_ACCEPT_MOTHER_H__

/* coordinate */
#define CONDITIONAL_ACCEPT_MOTHER_CONT_X          ((SCREEN_WIDTH - CONDITIONAL_ACCEPT_MOTHER_CONT_W) / 2)
#define CONDITIONAL_ACCEPT_MOTHER_CONT_Y          ((SCREEN_HEIGHT - CONDITIONAL_ACCEPT_MOTHER_CONT_H) / 2)
#define CONDITIONAL_ACCEPT_MOTHER_CONT_W          (SCREEN_WIDTH - 32)
#define CONDITIONAL_ACCEPT_MOTHER_CONT_H          (SCREEN_HEIGHT -76)

// frame
#define CONDITIONAL_ACCEPT_MOTHER_CA_FRM_X  10
#define CONDITIONAL_ACCEPT_MOTHER_CA_FRM_Y  70
#define CONDITIONAL_ACCEPT_MOTHER_CA_FRM_W  (CONDITIONAL_ACCEPT_MOTHER_CONT_W - 2 * CONDITIONAL_ACCEPT_MOTHER_CA_FRM_X)
#define CONDITIONAL_ACCEPT_MOTHER_CA_FRM_H  400

//title
#define CONDITIONAL_ACCEPT_MOTHER_TITLE_CNT      5
#define CONDITIONAL_ACCEPT_MOTHER_TITLE_X        10
#define CONDITIONAL_ACCEPT_MOTHER_TITLE_Y        10
#define CONDITIONAL_ACCEPT_MOTHER_TITLE_W        60
#define CONDITIONAL_ACCEPT_MOTHER_TITLE_H        35
#define CONDITIONAL_ACCEPT_MOTHER_TITLE_H_GAP    0

//list
#define CONDITIONAL_ACCEPT_MOTHER_LIST_X             10
#define CONDITIONAL_ACCEPT_MOTHER_LIST_Y             (CONDITIONAL_ACCEPT_MOTHER_TITLE_Y + CONDITIONAL_ACCEPT_MOTHER_TITLE_H + 6)
#define CONDITIONAL_ACCEPT_MOTHER_LIST_W             (CONDITIONAL_ACCEPT_MOTHER_CA_FRM_W - CONDITIONAL_ACCEPT_MOTHER_LIST_X * 2)
#define CONDITIONAL_ACCEPT_MOTHER_LIST_H             320

#define CONDITIONAL_ACCEPT_MOTHER_LIST_MID_L    0
#define CONDITIONAL_ACCEPT_MOTHER_LIST_MID_T    0
#define CONDITIONAL_ACCEPT_MOTHER_LIST_MID_W    (CONDITIONAL_ACCEPT_MOTHER_LIST_W - 2 * CONDITIONAL_ACCEPT_MOTHER_LIST_MID_L)
#define CONDITIONAL_ACCEPT_MOTHER_LIST_MID_H    (CONDITIONAL_ACCEPT_MOTHER_LIST_H - 2 * CONDITIONAL_ACCEPT_MOTHER_LIST_MID_T)

#define CONDITIONAL_ACCEPT_MOTHER_LIST_ITEM_V_GAP 0

//scroll
#define CONDITIONAL_ACCEPT_MOTHER_LIST_SBAR_X             (CONDITIONAL_ACCEPT_MOTHER_LIST_X + CONDITIONAL_ACCEPT_MOTHER_LIST_W)
#define CONDITIONAL_ACCEPT_MOTHER_LIST_SBAR_Y             CONDITIONAL_ACCEPT_MOTHER_LIST_Y
#define CONDITIONAL_ACCEPT_MOTHER_LIST_SBAR_W             16
#define CONDITIONAL_ACCEPT_MOTHER_LIST_SBAR_H             CONDITIONAL_ACCEPT_MOTHER_LIST_H

/* rect style */
#define RSI_CONDITIONAL_ACCEPT_MOTHER_FRM       RSI_WINDOW_1
/* font style */

/* others */
/*others*/
#define CONDITIONAL_ACCEPT_MOTHER_LIST_PAGE               8
#define CONDITIONAL_ACCEPT_MOTHER_LIST_FIELD_NUM          5


RET_CODE open_conditional_accept_mother(u32 para1, u32 para2);

#endif


